package com.example.kirchhoff.example.ui.recycler.fast

import android.os.Bundle
import android.support.v7.app.AppCompatActivity
import android.support.v7.widget.LinearLayoutManager
import android.support.v7.widget.RecyclerView
import com.example.kirchhoff.example.R
import java.util.*

class FastRecyclerViewActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.a_fast_recycler_view)

        val recyclerView = findViewById<RecyclerView>(R.id.recyclerView)
        recyclerView.layoutManager = LinearLayoutManager(this)
        recyclerView.adapter = FastRecyclerViewAdapter(mockData())
    }

    private fun mockData(): List<State> {
        val stateList = ArrayList<State>()
        stateList.add(State("Alabama", "AL"))
        stateList.add(State("Alaska", "AK"))
        stateList.add(State("Alberta", "AB"))
        stateList.add(State("American Samoa", "AS"))
        stateList.add(State("Arizona", "AZ"))
        stateList.add(State("Arkansas", "AR"))
        stateList.add(State("Armed Forces (AE)", "AE"))
        stateList.add(State("Armed Forces Americas", "AA"))
        stateList.add(State("Armed Forces Pacific", "AP"))
        stateList.add(State("British Columbia", "BC"))
        stateList.add(State("California", "CA"))
        stateList.add(State("Colorado", "CO"))
        stateList.add(State("Connecticut", "CT"))
        stateList.add(State("Delaware", "DE"))
        stateList.add(State("District Of Columbia", "DC"))
        stateList.add(State("Florida", "FL"))
        stateList.add(State("Georgia", "GA"))
        stateList.add(State("Guam", "GU"))
        stateList.add(State("Hawaii", "HI"))
        stateList.add(State("Idaho", "ID"))
        stateList.add(State("Illinois", "IL"))
        stateList.add(State("Indiana", "IN"))
        stateList.add(State("Iowa", "IA"))
        stateList.add(State("Kansas", "KS"))
        stateList.add(State("Kentucky", "KY"))
        stateList.add(State("Louisiana", "LA"))
        stateList.add(State("Maine", "ME"))
        stateList.add(State("Manitoba", "MB"))
        stateList.add(State("Maryland", "MD"))
        stateList.add(State("Massachusetts", "MA"))
        stateList.add(State("Michigan", "MI"))
        stateList.add(State("Minnesota", "MN"))
        stateList.add(State("Mississippi", "MS"))
        stateList.add(State("Missouri", "MO"))
        stateList.add(State("Montana", "MT"))
        stateList.add(State("Nebraska", "NE"))
        stateList.add(State("Nevada", "NV"))
        stateList.add(State("New Brunswick", "NB"))
        stateList.add(State("New Hampshire", "NH"))
        stateList.add(State("New Jersey", "NJ"))
        stateList.add(State("New Mexico", "NM"))
        stateList.add(State("New York", "NY"))
        stateList.add(State("Newfoundland", "NF"))
        stateList.add(State("North Carolina", "NC"))
        stateList.add(State("North Dakota", "ND"))
        stateList.add(State("Northwest Territories", "NT"))
        stateList.add(State("Nova Scotia", "NS"))
        stateList.add(State("Nunavut", "NU"))
        stateList.add(State("Ohio", "OH"))
        stateList.add(State("Oklahoma", "OK"))
        stateList.add(State("Ontario", "ON"))
        stateList.add(State("Oregon", "OR"))
        stateList.add(State("Pennsylvania", "PA"))
        stateList.add(State("Prince Edward Island", "PE"))
        stateList.add(State("Puerto Rico", "PR"))
        stateList.add(State("Quebec", "PQ"))
        stateList.add(State("Rhode Island", "RI"))
        stateList.add(State("Saskatchewan", "SK"))
        stateList.add(State("South Carolina", "SC"))
        stateList.add(State("South Dakota", "SD"))
        stateList.add(State("Tennessee", "TN"))
        stateList.add(State("Texas", "TX"))
        stateList.add(State("Utah", "UT"))
        stateList.add(State("Vermont", "VT"))
        stateList.add(State("Virgin Islands", "VI"))
        stateList.add(State("Virginia", "VA"))
        stateList.add(State("Washington", "WA"))
        stateList.add(State("West Virginia", "WV"))
        stateList.add(State("Wisconsin", "WI"))
        stateList.add(State("Wyoming", "WY"))
        stateList.add(State("Yukon Territory", "YT"))

        stateList.add(State("Alabama", "AL"))
        stateList.add(State("Alaska", "AK"))
        stateList.add(State("Alberta", "AB"))
        stateList.add(State("American Samoa", "AS"))
        stateList.add(State("Arizona", "AZ"))
        stateList.add(State("Arkansas", "AR"))
        stateList.add(State("Armed Forces (AE)", "AE"))
        stateList.add(State("Armed Forces Americas", "AA"))
        stateList.add(State("Armed Forces Pacific", "AP"))
        stateList.add(State("British Columbia", "BC"))
        stateList.add(State("California", "CA"))
        stateList.add(State("Colorado", "CO"))
        stateList.add(State("Connecticut", "CT"))
        stateList.add(State("Delaware", "DE"))
        stateList.add(State("District Of Columbia", "DC"))
        stateList.add(State("Florida", "FL"))
        stateList.add(State("Georgia", "GA"))
        stateList.add(State("Guam", "GU"))
        stateList.add(State("Hawaii", "HI"))
        stateList.add(State("Idaho", "ID"))
        stateList.add(State("Illinois", "IL"))
        stateList.add(State("Indiana", "IN"))
        stateList.add(State("Iowa", "IA"))
        stateList.add(State("Kansas", "KS"))
        stateList.add(State("Kentucky", "KY"))
        stateList.add(State("Louisiana", "LA"))
        stateList.add(State("Maine", "ME"))
        stateList.add(State("Manitoba", "MB"))
        stateList.add(State("Maryland", "MD"))
        stateList.add(State("Massachusetts", "MA"))
        stateList.add(State("Michigan", "MI"))
        stateList.add(State("Minnesota", "MN"))
        stateList.add(State("Mississippi", "MS"))
        stateList.add(State("Missouri", "MO"))
        stateList.add(State("Montana", "MT"))
        stateList.add(State("Nebraska", "NE"))
        stateList.add(State("Nevada", "NV"))
        stateList.add(State("New Brunswick", "NB"))
        stateList.add(State("New Hampshire", "NH"))
        stateList.add(State("New Jersey", "NJ"))
        stateList.add(State("New Mexico", "NM"))
        stateList.add(State("New York", "NY"))
        stateList.add(State("Newfoundland", "NF"))
        stateList.add(State("North Carolina", "NC"))
        stateList.add(State("North Dakota", "ND"))
        stateList.add(State("Northwest Territories", "NT"))
        stateList.add(State("Nova Scotia", "NS"))
        stateList.add(State("Nunavut", "NU"))
        stateList.add(State("Ohio", "OH"))
        stateList.add(State("Oklahoma", "OK"))
        stateList.add(State("Ontario", "ON"))
        stateList.add(State("Oregon", "OR"))
        stateList.add(State("Pennsylvania", "PA"))
        stateList.add(State("Prince Edward Island", "PE"))
        stateList.add(State("Puerto Rico", "PR"))
        stateList.add(State("Quebec", "PQ"))
        stateList.add(State("Rhode Island", "RI"))
        stateList.add(State("Saskatchewan", "SK"))
        stateList.add(State("South Carolina", "SC"))
        stateList.add(State("South Dakota", "SD"))
        stateList.add(State("Tennessee", "TN"))
        stateList.add(State("Texas", "TX"))
        stateList.add(State("Utah", "UT"))
        stateList.add(State("Vermont", "VT"))
        stateList.add(State("Virgin Islands", "VI"))
        stateList.add(State("Virginia", "VA"))
        stateList.add(State("Washington", "WA"))
        stateList.add(State("West Virginia", "WV"))
        stateList.add(State("Wisconsin", "WI"))
        stateList.add(State("Wyoming", "WY"))
        stateList.add(State("Yukon Territory", "YT"))

        return stateList
    }
}
