package com.kirchhoff.fastrecyclerview

import android.os.Bundle
import android.support.v7.app.AppCompatActivity
import android.support.v7.widget.LinearLayoutManager
import android.support.v7.widget.RecyclerView

class FastRecyclerViewActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.a_fast_recycler_view)

        val recyclerView = findViewById<RecyclerView>(R.id.recyclerView)
        recyclerView.layoutManager = LinearLayoutManager(this)
        recyclerView.adapter = FastRecyclerViewAdapter(mockData())
    }

    private fun mockData(): List<State> {
        return listOf(
                State("Alabama", "AL"),
                State("Alaska", "AK"),
                State("Alberta", "AB"),
                State("American Samoa", "AS"),
                State("Arizona", "AZ"),
                State("Arkansas", "AR"),
                State("Armed Forces (AE)", "AE"),
                State("Armed Forces Americas", "AA"),
                State("Armed Forces Pacific", "AP"),
                State("British Columbia", "BC"),
                State("California", "CA"),
                State("Colorado", "CO"),
                State("Connecticut", "CT"),
                State("Delaware", "DE"),
                State("District Of Columbia", "DC"),
                State("Florida", "FL"),
                State("Georgia", "GA"),
                State("Guam", "GU"),
                State("Hawaii", "HI"),
                State("Idaho", "ID"),
                State("Illinois", "IL"),
                State("Indiana", "IN"),
                State("Iowa", "IA"),
                State("Kansas", "KS"),
                State("Kentucky", "KY"),
                State("Louisiana", "LA"),
                State("Maine", "ME"),
                State("Manitoba", "MB"),
                State("Maryland", "MD"),
                State("Massachusetts", "MA"),
                State("Michigan", "MI"),
                State("Minnesota", "MN"),
                State("Mississippi", "MS"),
                State("Missouri", "MO"),
                State("Montana", "MT"),
                State("Nebraska", "NE"),
                State("Nevada", "NV"),
                State("New Brunswick", "NB"),
                State("New Hampshire", "NH"),
                State("New Jersey", "NJ"),
                State("New Mexico", "NM"),
                State("New York", "NY"),
                State("Newfoundland", "NF"),
                State("North Carolina", "NC"),
                State("North Dakota", "ND"),
                State("Northwest Territories", "NT"),
                State("Nova Scotia", "NS"),
                State("Nunavut", "NU"),
                State("Ohio", "OH"),
                State("Oklahoma", "OK"),
                State("Ontario", "ON"),
                State("Oregon", "OR"),
                State("Pennsylvania", "PA"),
                State("Prince Edward Island", "PE"),
                State("Puerto Rico", "PR"),
                State("Quebec", "PQ"),
                State("Rhode Island", "RI"),
                State("Saskatchewan", "SK"),
                State("South Carolina", "SC"),
                State("South Dakota", "SD"),
                State("Tennessee", "TN"),
                State("Texas", "TX"),
                State("Utah", "UT"),
                State("Vermont", "VT"),
                State("Virgin Islands", "VI"),
                State("Virginia", "VA"),
                State("Washington", "WA"),
                State("West Virginia", "WV"),
                State("Wisconsin", "WI"),
                State("Wyoming", "WY"),
                State("Yukon Territory", "YT"),
                State("Alabama", "AL"),
                State("Alaska", "AK"),
                State("Alberta", "AB"),
                State("American Samoa", "AS"),
                State("Arizona", "AZ"),
                State("Arkansas", "AR"),
                State("Armed Forces (AE)", "AE"),
                State("Armed Forces Americas", "AA"),
                State("Armed Forces Pacific", "AP"),
                State("British Columbia", "BC"),
                State("California", "CA"),
                State("Colorado", "CO"),
                State("Connecticut", "CT"),
                State("Delaware", "DE"),
                State("District Of Columbia", "DC"),
                State("Florida", "FL"),
                State("Georgia", "GA"),
                State("Guam", "GU"),
                State("Hawaii", "HI"),
                State("Idaho", "ID"),
                State("Illinois", "IL"),
                State("Indiana", "IN"),
                State("Iowa", "IA"),
                State("Kansas", "KS"),
                State("Kentucky", "KY"),
                State("Louisiana", "LA"),
                State("Maine", "ME"),
                State("Manitoba", "MB"),
                State("Maryland", "MD"),
                State("Massachusetts", "MA"),
                State("Michigan", "MI"),
                State("Minnesota", "MN"),
                State("Mississippi", "MS"),
                State("Missouri", "MO"),
                State("Montana", "MT"),
                State("Nebraska", "NE"),
                State("Nevada", "NV"),
                State("New Brunswick", "NB"),
                State("New Hampshire", "NH"),
                State("New Jersey", "NJ"),
                State("New Mexico", "NM"),
                State("New York", "NY"),
                State("Newfoundland", "NF"),
                State("North Carolina", "NC"),
                State("North Dakota", "ND"),
                State("Northwest Territories", "NT"),
                State("Nova Scotia", "NS"),
                State("Nunavut", "NU"),
                State("Ohio", "OH"),
                State("Oklahoma", "OK"),
                State("Ontario", "ON"),
                State("Oregon", "OR"),
                State("Pennsylvania", "PA"),
                State("Prince Edward Island", "PE"),
                State("Puerto Rico", "PR"),
                State("Quebec", "PQ"),
                State("Rhode Island", "RI"),
                State("Saskatchewan", "SK"),
                State("South Carolina", "SC"),
                State("South Dakota", "SD"),
                State("Tennessee", "TN"),
                State("Texas", "TX"),
                State("Utah", "UT"),
                State("Vermont", "VT"),
                State("Virgin Islands", "VI"),
                State("Virginia", "VA"),
                State("Washington", "WA"),
                State("West Virginia", "WV"),
                State("Wisconsin", "WI"),
                State("Wyoming", "WY"),
                State("Yukon Territory", "YT"))
    }
}
